services:
  - type: web
    name: whatsapp-bot
    env: node
    plan: free
    region: frankfurt
    branch: main
    buildCommand: npm install
    startCommand: node index.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
